from auth.application.base.errors import ApplicationError


class DataGatewayError(ApplicationError):
    ...
